### ISSUE TITLE
DHS P-3s

### ISSUE THREAD

**Issue by dziban303** [rikgale/VRSData#4]
Current active DHS/CBP P-3s. Data from www.p3orion.nl, checked jetphotos too to verify. 

A4B960 and A5EA33 lack the 'LRT' in the `Type` field that the other slicks have, while A5085E is still coded as a P-3AM in the latest Aircraft.csv. A0D900 is in the csv as well as a CBP bird, but it's been dereg'd and turned into soda cans by now. 

```
A4B960 / N403SK / Lockheed P-3BLRT Orion / built 1968 / USDHS-P3
A5085E / N423SK / Lockheed P-3BLRT Orion / built 1967 / USDHS-P3
A5286F / N431SK / built 1967 / USDHS-P3
AA6491 / N769SK / built 1966 / USDHS-P3
A9F7DB / N741SK / built 1966 / USDHS-P3
A5EA33 / N480SK / Lockheed P-3BLRT Orion / built 1968 / USDHS-P3

A0AA61 / N142CS / built 1967 / USDHS-P3RDR
A0AE18 / N143CS / built 1967 / USDHS-P3RDR
A0B1CF / N144CS / built 1967 / USDHS-P3RDR
A0B586 / N145CS / built 1968 / USDHS-P3RDR
A0B93D / N146CS / built 1968 / USDHS-P3RDR
A0BCF4 / N147CS / built 1966 / USDHS-P3RDR
A0C0AB / N148CS / built 1967 / USDHS-P3RDR
A0C462 / N149CS / built 1968 / USDHS-P3RDR

A0D900 / N15390 / deregistered, scrapped, fuselage auctioned april 2013
```

And because it wouldn't be a database update without a Texan or two,

`AE4EA0 / CNV-TEX2`

Lastly, spotted this guy who had an N-number/hex change. It used to be `A81525 / N62NW`, but it's now changed to `A38CDB / N328JL`, same F900, same owner.

Cheers

**Comment by rikgale** [comment]
Updated the P-3s.
The one you mentioned was updated, but you only posted this about 10 mins post nightly update, so you may have had the prev days data.
Going to keep an eye on the change one, but otherwise not touch it. I would like to see if the semi-automated process will update it in time.
Added the TEX2, have added a few of my own today as well.
All the above should update on GH at 02:30 Zulu 01/03/23 - unless my updated backup script has not worked again.
