### ISSUE TITLE
a few more

### ISSUE THREAD

**Issue by dziban303** [rikgale/VRSData#8]
---
# 2023-03-04

A47CF9 / CAP-C172
N26XP / serial HA-0152
AD206D / serial 45-109
A0B580 / GEN-EC45
A341CD / GEN-SF50

# 2023-03-05

AE29DD / RCH-C30J
AE54F4 / Raytheon Aircraft Company T-6B Texan II / serial PN-217 / United States Navy / CNV-TEX2

**Comment by rikgale** [comment]
Hey. Thanks for info.
A0B580 / GEN-EC45 <-- I have created a side for this one MERTOAVEC45. Will be in next update
A341CD / GEN-SF50 <-- as above LEBEOUFBROS (no decent sides of this frame, so logo only)
All updated as some side views / logos made.
Unless you are particularly keen to record serial numbers, don't worry too hard. If the serials come with other info then happy to add, but otherwise personally not to bothered.
Cheers again. :)
